spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#IMPORTANTE: Para configurar la api ir a https://rapidapi.com/developer/dashboard
weather:
  api:
    host: INSERTA_TU_HOST_ACA
    key: INSERTA_TU_KEY_ACA
    url: INSERTA_TU_URL_ACA
