/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cl.dtoros.weather.poc

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class Main

fun main(args: Array<String>) {
    runApplication<Main>(*args)
}
